### PR TITLE
Added .left MarqueeType

### PR DESCRIPTION
**Pull request by Daltron**
Hey @cbpowell! 😄 I finally got around to this and I would love to know what you think. I mentioned this in #185. I also updated the storyboard with an example of this type. My repo [NotificationBanner](https://github.com/Daltron/NotificationBanner) is greatly in need of this marquee type and I'd love to get this in the next release.
Thanks!

marquee_label_left

### CODE REVIEW

**Comment by cbpowell** [comment]
Ah man, I've been working on this (indirectly) myself - wish I'd pushed it a little earlier to save you some trouble!

Check out the [newest commit to the dev branch](https://github.com/cbpowell/MarqueeLabel/commit/44ec6978f05e2468e4ad0d4110759d48bac69ab6) which implements a way to build custom MarqueeLabel scroll styles using a sequence/array of [`MarqueeSteps`](https://github.com/cbpowell/MarqueeLabel/blob/44ec6978f05e2468e4ad0d4110759d48bac69ab6/Sources/Swift/MarqueeLabel.swift#L1544-L1548). You can build sequence of steps that define the label position, timing, and edge fades. You can see how the "default" Marquee types are built up using these steps [here](https://github.com/cbpowell/MarqueeLabel/blob/44ec6978f05e2468e4ad0d4110759d48bac69ab6/Sources/Swift/MarqueeLabel.swift#L649-L660).

So I actually haven't had time to test out a true "custom" sequence yet, but you should be able to implement what you're thinking of with something like the below (drawing from the default `.leftRight` type).

```swift
// While configuring the label text, type, etc…
let animationDelay = … // Your delay CGFloat value
let animationDuration = … // Your animation duration CGFloat value
let endStateDelay = BIG_VAL_HERE; // Some big value to hold the label at the away position
let sequence = [
    ScrollStep(timeStep: 0.0, position: .home, edgeFades: .trailing),               // Starting point, at home, with trailing fade
    ScrollStep(timeStep: animationDelay, position: .home, edgeFades: .trailing),    // Delay at home, maintaining fade state
    FadeStep(timeStep: 0.2, edgeFades: [.leading, .trailing]),                      // 0.2 sec after delay ends, fade leading edge in as well
    FadeStep(timeStep: -0.2, edgeFades: [.leading, .trailing]),                     // Maintain fade state until 0.2 sec before reaching the below away position
    ScrollStep(timeStep: animationDuration, timingFunction: animationCurve,         // Away position, using animationCurve transition, with only leading edge faded in
          position: .away, edgeFades: .leading),
    ScrollStep(timeStep: endStateDelay, position: .away, edgeFades: .leading)       // Delay at away, maintaining fade state, holding here until Notification is dismissed/animates away
];

labelInstance.scrollSteps = sequence;
```
So this sequence has a delay at the home position, then takes the specified duration to animate, and then has a _long_ "delay" at the end away position - i.e., long enough that your notification would be dismissed/actioned/closed before it ever expired.

If you don't mind, want to give it a test run with your use case?

As far as I can tell from some limited testing, all the default Marquee types work just fine. I hadn't pushed it to master yet because I was trying to figure out the best way to replicate the way the `.continuous` type currently starts the edge fade animation just-in-time based on the timing function. It's easy to do internally, but I figured it might be worth exposing a way to do it to developers (who might come up with other cool uses).

**Comment by Daltron** [comment]
@cbpowell Glad to hear new additions are on the way! With the `MarqueeSteps` addition, do you plan on removing the `MarqueeType` from the labels or will they stay? If they are staying, would it make sense to make this particular `MarqueeType` a default one so it is easily accessible instead of having to create this via the new `MarqueeSteps` way? I feel like this `MarqueeType` is an extremely common use case that many would appreciate having directly at their disposal.

**Comment by cbpowell** [comment]
I wasn't planning on removing the default types, as MarqueeLabel actually still needs to know what type is desired in order to calculate the home/away positions. I suppose that could be built into the steps somehow, but I'm thinking it's better to abstract those details away?

I'm not opposed to keeping a `.left` and .`right` types, although there might have to be a little additional configuration specific to those. They would maybe want to default to keeping the animation around indefinitely (`.removedOnCompletion = true`), since the end state delay would vary depending on what you wanted it for.

**Comment by Daltron** [comment]
@cbpowell You can go ahead and close this if you don't think it fits quite right with the future of MarqueeLabel as I completely understand. I might end up implementing something custom for [NotificationBanner](https://github.com/Daltron/NotificationBanner) that simply scrolls from left to right since that is really the only feature that I need.

**Comment by cbpowell** [comment]
Well I was leaning towards including the proposed `.left` and `.right` types, especially since the ScrollSteps buildup method makes the code much easier to maintain. It might not be in this pull request since we went in different directions, though. But I'm thinking it also lets you do exactly what you were looking to do? Even without the dedicated `.left` type.

**Comment by cbpowell** [comment]
I've added a defined `.left` type in the newest commit on `dev` (8270a89b745d9a4214a6d8b66312135f1e8eb556) - give it a try! It was super quick. I just made the last step time the max value a CGFloat can store...I don't think there's really a big impact to keeping the animation around that way.

**Comment by cbpowell** [comment]
I've implemented `.left` and `.right` types in the Swift code (along with the the new custom sequence functionality), and was _about_ to push release 3.1.0.

…but I should at least implement the `.left` and `.right` types in the Objective-C code I think. That said, I think the current Swift code is ready to go!

**Comment by Daltron** [comment]
@cbpowell this sounds great! Let me know when 3.1.0 is released and I will add it asap to [NotificationBanner](https://github.com/Daltron/NotificationBanner)

**Comment by cbpowell** [comment]
Just pushed [release 3.1.0](https://github.com/cbpowell/MarqueeLabel/releases/tag/3.1.0)! Let me know if anything with the `left` type doesn't work as expected!

**Comment by Daltron** [comment]
@cbpowell Thanks a lot! Its working perfectly! 👍 👍 👍

**Pull request closed without merging**
