### PR TITLE
add forced scrolling feature

### PR DESCRIPTION
**Pull request by hariseldon78**
Hi guys, i'm using this little variation in my application to force a label to scroll even if the text fits inside, to create a "banner" effect. I don't know if it's in the interest of the project, merge it if you see fit.

### CODE REVIEW

**Comment by cbpowell** [comment]
Thanks for putting it together! I've always held off from adding this type of feature to the core code in the past, because I thought there would be some tricky edge cases and it isn't in what I consider to be the primary featureset of MarqueeLabel.

But - people have asked for it a lot, and I was thinking about adding a (Swift-only) "extensions library" of contributed code for such features. The extensions wouldn't be included in the main code, but people could come grab them from here if they wanted the functionality. I'll play around with the idea with this code - one downside is it will have to be a `private` extension, which means people would need to modify the actual `MarqueeLabel.swift` file manually to include, I think.

**Comment by hariseldon78** [comment]
please note that modifying a library file is not a viable solution if the
library is imported via cocoapods. the cleanest way to do that is to fork
the library, but then you have to mantain the fork updated with
mainstream..
Il giorno mer 13 lug 2016 alle 16:33 Charles Powell <
notifications@github.com> ha scritto:

**Comment by omarojo** [comment]
Is this feature available ?

**Comment by hariseldon78** [comment]
> Is this feature available ?

No, the pull request was never accepted. I suggest you fork the project and redo it yourself, after all is 3 lines of code...

**Comment by cbpowell** [comment]
I just needed to think about it for ~5 years… 😉 

In order to be compatible with `continuous` type labels, I added a calculation to determine the replication count. Otherwise for very short labels you'd get the 2nd "fake" label which would animate into place correctly, but there would be a large blank space to the right/left of the text, followed by a another text instance popping into place when the animation looped.

**Pull request merged**
