### PR TITLE
Add Package.swift for swift package manager

### PR DESCRIPTION
**Pull request by rollmind**
I'm add setting for Swift Package Manager for this library to prepare coming Xcode 11.
thanks.

### CODE REVIEW

**Comment by cbpowell** [comment]
Thanks! Much better than the SPM file I had before - but that said, I removed it because apparently it was failing with Carthage: #239.

I mostly find Carthage more trouble than it's worth, but I guess I'll check whether or not this works with Carthage before merging. Also is there any reason to include macOS in compatible platforms at this point?

**Comment by cbpowell** [comment]
@d-date I'm able to build my MarqueeLabel+Carthage test project with @rollmind's SPM file (although with [this Carthage workaround](https://github.com/Carthage/Carthage/issues/2825) for Xcode 11b4). For now I'll merge this into the Xcode11 branch.

**Comment by rollmind** [comment]
> Thanks! Much better than the SPM file I had before - but that said, I removed it because apparently it was failing with Carthage: #238 & #239.
> 
> I mostly find Carthage more trouble than it's worth, but I guess I'll check whether or not this works with Carthage before merging. Also is there any reason to include macOS in compatible platforms at this point?

I did not know that. My test is not good enough. thank you.

**Comment by cbpowell** [comment]
Well to clarify a little, it seems to cause far more issues and work for me as the maintainer. When using it to add and use libraries I think it works reasonably well, but I haven't used it very much.

**Pull request merged**
